version: '3.6'
services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: antadmin
      MYSQL_ROOT_PASSWORD: 1234567890
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    security_opt:
      - seccomp:unconfined

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
