# HTTP Server
[server]
	address       = ":8199"
	serverRoot    = "public"
    dumpRouterMap = false
	serverAgent   = "antbiz"
    sessionIdName = "x-api-sid"
    logPath       = "./log/server"

# Logger.
[logger]
    path        = "./log"
    level       = "all"
    stdout      = true

# Template.
[viewer]
    path        = "template"
    defaultFile = "index.html"
    delimiters  =  ["${", "}"]

# Database.
[database]
    [database.logger]
        path   = "./log/sql"
        level  = "all"
        stdout = true
    [database.default]
        type   = "mysql"
        link   = "root:1234567890@tcp(127.0.0.1:3306)/antadmin"
        debug  = true

# Redis数据库配置
[redis]
    default = "127.0.0.1:6379,0"
    cache   = "127.0.0.1:6379,1,123456?idleTimeout=600"
