// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MenusColumns holds the columns for the "menus" table.
	MenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "hide", Type: field.TypeBool, Default: false},
		{Name: "path", Type: field.TypeString},
		{Name: "sort", Type: field.TypeInt, Default: 0},
		{Name: "icon", Type: field.TypeString},
		{Name: "parent", Type: field.TypeString},
	}
	// MenusTable holds the schema information for the "menus" table.
	MenusTable = &schema.Table{
		Name:        "menus",
		Columns:     MenusColumns,
		PrimaryKey:  []*schema.Column{MenusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "menu_created_at",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[1]},
			},
			{
				Name:    "menu_created_by",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MenusTable,
	}
)

func init() {
}
